const API_BASE = window.HYPERAPEX_API_BASE || 'http://localhost:4000';
const token = sessionStorage.getItem('hyperapex_token');
if (!token) window.location.replace('login.html');
async function api(path, options = {}) { const headers={...(options.headers||{}),Authorization:`Bearer ${token}`}; const response=await fetch(`${API_BASE}${path}`,{...options,headers}); if(response.status===401){sessionStorage.clear();window.location.replace('login.html');throw new Error('Authentication required.');} return response; }
async function loadServices(){const grid=document.getElementById('serviceGrid');try{const r=await api('/api/services');if(!r.ok)throw new Error();const services=await r.json();document.getElementById('servicesCount').textContent=services.length;grid.innerHTML=services.map(s=>`<article class="service-card"><p class="eyebrow">${escapeHtml(s.category)}</p><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description||'')}</p></article>`).join('');populateServiceOptions(services);}catch(_e){grid.innerHTML='<p>Unable to load services.</p>';}}
async function loadClients(){const rows=document.getElementById('clientRows');try{const r=await api('/api/clients');if(!r.ok)throw new Error();const clients=await r.json();document.getElementById('clientsCount').textContent=clients.length;window.clientData=clients;rows.innerHTML=clients.length?clients.map(c=>`<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.client_type)}</td><td>${escapeHtml(c.email||'—')}</td><td>${escapeHtml(c.phone||'—')}</td><td>${escapeHtml(c.status)}</td></tr>`).join(''):'<tr><td colspan="5">No clients yet.</td></tr>';populateClientOptions(clients);}catch(_e){rows.innerHTML='<tr><td colspan="5">Unable to load clients.</td></tr>';}}
async function loadRequests(){const rows=document.getElementById('requestRows');try{const r=await api('/api/requests');if(!r.ok)throw new Error();const requests=await r.json();document.getElementById('requestsCount').textContent=requests.filter(x=>!['COMPLETED','CANCELLED'].includes(x.status)).length;rows.innerHTML=requests.length?requests.map(x=>`<tr><td>${escapeHtml(x.title)}</td><td>${escapeHtml(x.client_name)}</td><td>${escapeHtml(x.service_name)}</td><td><select data-request-status="${x.id}">${['NEW','DOCUMENTS_REQUIRED','IN_PROGRESS','AWAITING_CLIENT','UNDER_REVIEW','COMPLETED','CANCELLED'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${escapeHtml(x.priority)}</td><td>${escapeHtml(x.due_date||'—')}</td></tr>`).join(''):'<tr><td colspan="6">No service requests yet.</td></tr>';document.querySelectorAll('[data-request-status]').forEach(el=>el.addEventListener('change',()=>updateRequestStatus(el.dataset.requestStatus,el.value)));}catch(_e){rows.innerHTML='<tr><td colspan="6">Unable to load requests.</td></tr>';}}
async function loadTasks(){const rows=document.getElementById('taskRows');try{const r=await api('/api/tasks');if(!r.ok)throw new Error();const tasks=await r.json();document.getElementById('tasksCount').textContent=tasks.filter(x=>x.status!=='DONE').length;rows.innerHTML=tasks.length?tasks.map(x=>`<tr><td>${escapeHtml(x.title)}</td><td>${escapeHtml(x.assignee_name||'Unassigned')}</td><td>${escapeHtml(x.status)}</td><td>${escapeHtml(x.due_date||'—')}</td></tr>`).join(''):'<tr><td colspan="4">No tasks yet.</td></tr>';}catch(_e){rows.innerHTML='<tr><td colspan="4">Unable to load tasks.</td></tr>';}}
async function updateRequestStatus(id,status){const r=await api(`/api/requests/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!r.ok){alert('Unable to update request status.');return;}loadRequests();}
function populateClientOptions(clients){const select=document.getElementById('requestClient');if(!select)return;select.innerHTML='<option value="">Select client</option>'+clients.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');}
function populateServiceOptions(services){const select=document.getElementById('requestService');if(!select)return;select.innerHTML='<option value="">Select service</option>'+services.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');}
function setupClientForm(){const form=document.getElementById('clientForm');document.getElementById('showClientForm').addEventListener('click',()=>{form.hidden=false;document.getElementById('clientName').focus();});document.getElementById('cancelClient').addEventListener('click',()=>{form.reset();form.hidden=true;});form.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('clientMessage');msg.textContent='Saving…';try{const r=await api('/api/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_type:document.getElementById('clientType').value,name:document.getElementById('clientName').value.trim(),email:document.getElementById('clientEmail').value.trim()||null,phone:document.getElementById('clientPhone').value.trim()||null,address:document.getElementById('clientAddress').value.trim()||null,notes:document.getElementById('clientNotes').value.trim()||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save client.');msg.textContent='Client saved successfully.';form.reset();setTimeout(()=>{form.hidden=true;msg.textContent='';},700);loadClients();}catch(error){msg.textContent=error.message;}});}
function setupRequestForm(){const form=document.getElementById('requestForm');document.getElementById('showRequestForm').addEventListener('click',()=>{form.hidden=false;});document.getElementById('cancelRequest').addEventListener('click',()=>{form.reset();form.hidden=true;});form.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('requestMessage');msg.textContent='Saving…';try{const r=await api('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:Number(document.getElementById('requestClient').value),service_id:Number(document.getElementById('requestService').value),title:document.getElementById('requestTitle').value.trim(),description:document.getElementById('requestDescription').value.trim()||null,priority:document.getElementById('requestPriority').value,due_date:document.getElementById('requestDue').value||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create request.');msg.textContent='Service request created.';form.reset();setTimeout(()=>{form.hidden=true;msg.textContent='';},700);loadRequests();}catch(error){msg.textContent=error.message;}});}
function setupUser(){const user=JSON.parse(sessionStorage.getItem('hyperapex_user')||'null');if(user)document.querySelector('.topbar h1').textContent=`Welcome, ${user.full_name.split(' ')[0]}`;document.querySelector('.logout')?.addEventListener('click',e=>{e.preventDefault();sessionStorage.clear();window.location.href='login.html';});}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
setupUser();setupClientForm();setupRequestForm();loadServices();loadClients();loadRequests();loadTasks();
