require('dotenv').config();
const express=require('express');const helmet=require('helmet');const cors=require('cors');const mysql=require('mysql2/promise');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const requestRoutes=require('./routes/requests');
const app=express();const port=Number(process.env.PORT||4000);const jwtSecret=process.env.JWT_SECRET;if(!jwtSecret)throw new Error('JWT_SECRET is required.');app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:process.env.CORS_ORIGIN||false,credentials:true}));app.use(express.json({limit:'1mb'}));
let pool;function getPool(){if(!pool)pool=mysql.createPool({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,waitForConnections:true,connectionLimit:10,enableKeepAlive:true});return pool;}function signUser(user){return jwt.sign({sub:user.id,role:user.role,email:user.email,client_id:user.client_id||null},jwtSecret,{expiresIn:process.env.JWT_EXPIRES_IN||'8h'});}function auth(requiredRoles=[]){return async(req,res,next)=>{try{const h=req.get('authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Authentication required.'});const p=jwt.verify(t,jwtSecret);if(requiredRoles.length&&!requiredRoles.includes(p.role))return res.status(403).json({error:'Insufficient permissions.'});req.user=p;next();}catch(_e){return res.status(401).json({error:'Invalid or expired authentication token.'});}};}
app.get('/api/health',async(_req,res)=>{try{await getPool().query('SELECT 1');res.json({status:'ok',service:'hyperapex-business-hub-api',database:'ok'});}catch(_e){res.status(503).json({status:'degraded',service:'hyperapex-business-hub-api',database:'unavailable'});}});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email and password are required.'});try{const[rows]=await getPool().query('SELECT id,full_name,email,password_hash,role,status,client_id FROM users WHERE email=? LIMIT 1',[email]);const user=rows[0];if(!user||user.status!=='ACTIVE'||!(await bcrypt.compare(password,user.password_hash)))return res.status(401).json({error:'Invalid email or password.'});res.json({token:signUser(user),user:{id:user.id,full_name:user.full_name,email:user.email,role:user.role,client_id:user.client_id||null}});}catch(_e){res.status(500).json({error:'Unable to complete login.'});}});
app.get('/api/auth/me',auth(),async(req,res)=>{try{const[rows]=await getPool().query('SELECT id,full_name,email,role,status,client_id FROM users WHERE id=? LIMIT 1',[req.user.sub]);if(!rows[0]||rows[0].status!=='ACTIVE')return res.status(401).json({error:'Account unavailable.'});res.json({user:rows[0]});}catch(_e){res.status(500).json({error:'Unable to load account.'});}});
app.get('/api/services',async(_req,res)=>{try{const[rows]=await getPool().query('SELECT id,category,name,slug,description FROM services WHERE active=TRUE ORDER BY category,name');res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load services.'});}});
app.get('/api/clients',auth(['ADMIN','STAFF','SPECIALIST']),async(_req,res)=>{try{const[rows]=await getPool().query('SELECT id,client_type,name,email,phone,address,status,created_at FROM clients ORDER BY created_at DESC');res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load clients.'});}});
app.post('/api/clients',auth(['ADMIN','STAFF']),async(req,res)=>{const{client_type='INDIVIDUAL',name,email=null,phone=null,address=null,notes=null}=req.body;if(!name||!String(name).trim())return res.status(400).json({error:'Client name is required.'});try{const[result]=await getPool().execute('INSERT INTO clients(client_type,name,email,phone,address,notes) VALUES(?,?,?,?,?,?)',[client_type,String(name).trim(),email,phone,address,notes]);res.status(201).json({id:result.insertId,message:'Client created.'});}catch(_e){res.status(500).json({error:'Unable to create client.'});}});
app.get('/api/documents',auth(['ADMIN','STAFF','SPECIALIST']),async(req,res)=>{try{let sql=`SELECT d.id,d.client_id,c.name client_name,d.original_name,d.mime_type,d.file_size,d.created_at,u.full_name uploaded_by_name FROM documents d JOIN clients c ON c.id=d.client_id LEFT JOIN users u ON u.id=d.uploaded_by WHERE 1=1`,p=[];if(req.query.client_id){sql+=' AND d.client_id=?';p.push(Number(req.query.client_id));}sql+=' ORDER BY d.created_at DESC';const[rows]=await getPool().query(sql,p);res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load documents.'});}});
app.use('/api/requests',requestRoutes(getPool(),auth));
app.use((_req,res)=>res.status(404).json({error:'Route not found.'}));app.listen(port,()=>console.log(`Hyperapex Business Hub API listening on port ${port}`));
