require('dotenv').config();
const express=require('express');const helmet=require('helmet');const cors=require('cors');const mysql=require('mysql2/promise');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const financeRoutes=require('./routes/finance');const paymentRoutes=require('./routes/payments');const documentRoutes=require('./routes/documents');const reportRoutes=require('./routes/reports');const exportRoutes=require('./routes/exports');const pdfReportRoutes=require('./routes/pdfReports');const clientAccountRoutes=require('./routes/clientAccounts');const requestRoutes=require('./routes/requests');const matterFileRoutes=require('./routes/matterFiles');const notificationRoutes=require('./routes/notifications');const taskRoutes=require('./routes/tasks');const {authLimiter,apiLimiter,validateEnv,errorHandler}=require('./middleware/security');
validateEnv();
const app=express();const port=Number(process.env.PORT||4000);const jwtSecret=process.env.JWT_SECRET;app.disable('x-powered-by');app.set('trust proxy',process.env.TRUST_PROXY==='true'?1:false);app.use(helmet());app.use(cors({origin:process.env.CORS_ORIGIN||false,credentials:true}));app.use(express.json({limit:'1mb'}));app.use('/api',apiLimiter);
let pool;function getPool(){if(!pool)pool=mysql.createPool({host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,waitForConnections:true,connectionLimit:10,enableKeepAlive:true});return pool;}function signUser(user){return jwt.sign({sub:user.id,role:user.role,email:user.email,client_id:user.client_id||null},jwtSecret,{expiresIn:process.env.JWT_EXPIRES_IN||'8h'});}function auth(requiredRoles=[]){return async(req,res,next)=>{try{const h=req.get('authorization')||'';const t=h.startsWith('Bearer ')?h.slice(7):null;if(!t)return res.status(401).json({error:'Authentication required.'});const p=jwt.verify(t,jwtSecret);if(requiredRoles.length&&!requiredRoles.includes(p.role))return res.status(403).json({error:'Insufficient permissions.'});if(p.role==='CLIENT'&&!p.client_id)return res.status(403).json({error:'Client portal account is not linked to a client.'});req.user=p;next();}catch(_e){return res.status(401).json({error:'Invalid or expired authentication token.'});}};}
app.get('/api/health',async(_req,res)=>{try{await getPool().query('SELECT 1');res.json({status:'ok',service:'hyperapex-business-hub-api',database:'ok'});}catch(_e){res.status(503).json({status:'degraded',service:'hyperapex-business-hub-api',database:'unavailable'});}});
app.post('/api/auth/login',authLimiter,async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email||!password)return res.status(400).json({error:'Email and password are required.'});try{const[rows]=await getPool().query('SELECT id,full_name,email,password_hash,role,status,client_id FROM users WHERE email=? LIMIT 1',[email]);const user=rows[0];if(!user||user.status!=='ACTIVE'||!(await bcrypt.compare(password,user.password_hash)))return res.status(401).json({error:'Invalid email or password.'});if(user.role==='CLIENT'&&!user.client_id)return res.status(403).json({error:'Client account is not linked to a client record.'});res.json({token:signUser(user),user:{id:user.id,full_name:user.full_name,email:user.email,role:user.role,client_id:user.client_id||null}});}catch(_e){res.status(500).json({error:'Unable to complete login.'});}});
app.get('/api/auth/me',auth(),async(req,res)=>{try{const[rows]=await getPool().query('SELECT id,full_name,email,role,status,client_id FROM users WHERE id=? LIMIT 1',[req.user.sub]);if(!rows[0]||rows[0].status!=='ACTIVE')return res.status(401).json({error:'Account unavailable.'});if(rows[0].role==='CLIENT'&&!rows[0].client_id)return res.status(403).json({error:'Client portal account is not linked.'});res.json({user:rows[0]});}catch(_e){res.status(500).json({error:'Unable to load account.'});}});
app.get('/api/services',async(_req,res)=>{try{const[rows]=await getPool().query('SELECT id,category,name,slug,description FROM services WHERE active=TRUE ORDER BY category,name');res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load services.'});}});
app.get('/api/clients',auth(['ADMIN','STAFF','SPECIALIST']),async(_req,res)=>{try{const[rows]=await getPool().query('SELECT id,client_type,name,email,phone,address,status,created_at FROM clients ORDER BY created_at DESC');res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load clients.'});}});
app.post('/api/clients',auth(['ADMIN','STAFF']),async(req,res)=>{const{client_type='INDIVIDUAL',name,email=null,phone=null,address=null,notes=null}=req.body;if(!name||!String(name).trim())return res.status(400).json({error:'Client name is required.'});try{const[result]=await getPool().execute('INSERT INTO clients(client_type,name,email,phone,address,notes) VALUES(?,?,?,?,?,?)',[client_type,String(name).trim(),email,phone,address,notes]);res.status(201).json({id:result.insertId,message:'Client created.'});}catch(_e){res.status(500).json({error:'Unable to create client.'});}});
app.get('/api/documents',auth(['ADMIN','STAFF','SPECIALIST','CLIENT']),async(req,res)=>{const requested=req.query.client_id?Number(req.query.client_id):null,r=req.query.request_id?Number(req.query.request_id):null;if(req.user.role==='CLIENT'&&requested&&requested!==Number(req.user.client_id))return res.status(403).json({error:'Access denied.'});const c=req.user.role==='CLIENT'?Number(req.user.client_id):requested;try{let sql=`SELECT d.id,d.client_id,c.name client_name,d.request_id,d.original_name,d.mime_type,d.file_size,d.created_at,u.full_name uploaded_by_name FROM documents d JOIN clients c ON c.id=d.client_id LEFT JOIN users u ON u.id=d.uploaded_by WHERE 1=1`,p=[];if(c){sql+=' AND d.client_id=?';p.push(c);}if(r){sql+=' AND d.request_id=?';p.push(r);}sql+=' ORDER BY d.created_at DESC';const[rows]=await getPool().query(sql,p);res.json(rows);}catch(_e){res.status(500).json({error:'Unable to load document records.'});}});
app.post('/api/documents',auth(['ADMIN','STAFF','SPECIALIST']),async(req,res)=>{const{client_id,request_id=null,original_name,storage_key,mime_type=null,file_size=null}=req.body;if(!client_id||!original_name||!storage_key)return res.status(400).json({error:'Client, original file name and storage key are required.'});try{const[result]=await getPool().execute('INSERT INTO documents(client_id,request_id,uploaded_by,original_name,storage_key,mime_type,file_size) VALUES(?,?,?,?,?,?,?)',[client_id,request_id,req.user.sub,String(original_name),String(storage_key),mime_type,file_size]);await getPool().execute('INSERT INTO activity_logs(user_id,action,entity_type,entity_id,details) VALUES(?,?,?,?,?)',[req.user.sub,'CREATE','DOCUMENT',result.insertId,JSON.stringify({client_id,request_id,original_name})]);res.status(201).json({id:result.insertId,message:'Document record created.'});}catch(_e){res.status(500).json({error:'Unable to create document record.'});}});
app.delete('/api/documents/:id',auth(['ADMIN']),async(req,res)=>{try{const[result]=await getPool().execute('DELETE FROM documents WHERE id=?',[req.params.id]);if(!result.affectedRows)return res.status(404).json({error:'Document record not found.'});res.json({message:'Document record deleted.'});}catch(_e){res.status(500).json({error:'Unable to delete document record.'});}});
app.use('/api/requests',requestRoutes(getPool(),auth));app.use('/api/matter-files',matterFileRoutes(getPool(),auth));app.use('/api/notifications',notificationRoutes(getPool(),auth));app.use('/api/tasks',taskRoutes(getPool(),auth));app.use('/api/finance',financeRoutes(getPool(),auth));app.use('/api/payments',paymentRoutes(getPool(),auth));app.use('/api/documents',documentRoutes(getPool(),auth));app.use('/api/reports',reportRoutes(getPool(),auth));app.use('/api/exports',exportRoutes(getPool(),auth));app.use('/api/pdf-reports',pdfReportRoutes(getPool(),auth));app.use('/api/client-accounts',clientAccountRoutes(getPool(),auth));
app.use((_req,res)=>res.status(404).json({error:'Route not found.'}));app.use(errorHandler);app.listen(port,()=>console.log(`Hyperapex Business Hub API listening on port ${port}`));
