const express=require('express');const router=express.Router();
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function csv(rows,headers){return [headers.map(csvEscape).join(','),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\n');}
module.exports=function(pool,auth){
 router.get('/executive.csv',auth(['ADMIN']),async(_req,res)=>{try{const[[clients]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status='ACTIVE'),0) active FROM clients`);const[[requests]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status NOT IN ('COMPLETED','CLOSED')),0) open,COALESCE(SUM(status='COMPLETED'),0) completed,COALESCE(SUM(status='CLOSED'),0) closed FROM service_requests`);const[[tasks]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status IN ('TODO','IN_PROGRESS','BLOCKED')),0) open,COALESCE(SUM(status='COMPLETED'),0) completed,COALESCE(SUM(status NOT IN ('COMPLETED','CANCELLED') AND due_date<CURDATE()),0) overdue FROM matter_tasks`);const[[finance]]=await pool.query(`SELECT COUNT(*) invoice_count,COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected,COALESCE(SUM(balance_due),0) outstanding FROM invoices WHERE status<>'VOID'`);const rows=[{metric:'Total Clients',value:clients.total},{metric:'Active Clients',value:clients.active},{metric:'Total Matters',value:requests.total},{metric:'Open Matters',value:requests.open},{metric:'Completed Matters',value:requests.completed},{metric:'Closed Matters',value:requests.closed},{metric:'Total Tasks',value:tasks.total},{metric:'Open Tasks',value:tasks.open},{metric:'Completed Tasks',value:tasks.completed},{metric:'Overdue Tasks',value:tasks.overdue},{metric:'Invoices',value:finance.invoice_count},{metric:'Total Invoiced (KES)',value:finance.invoiced},{metric:'Collected (KES)',value:finance.collected},{metric:'Outstanding (KES)',value:finance.outstanding}];res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-executive-report.csv"');res.send(csv(rows,['metric','value']));}catch(_e){res.status(500).json({error:'Unable to export executive report.'});}});
 router.get('/invoices.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT i.invoice_number,c.name client_name,i.issue_date,i.due_date,i.status,i.total_amount,i.amount_paid,i.balance_due FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.status<>'VOID' ORDER BY i.issue_date DESC`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-invoice-report.csv"');res.send(csv(rows,['invoice_number','client_name','issue_date','due_date','status','total_amount','amount_paid','balance_due']));}catch(_e){res.status(500).json({error:'Unable to export invoice report.'});}});
 router.get('/payments.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT p.receipt_number,p.payment_date,i.invoice_number,c.name client_name,p.method,p.reference,p.amount FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN clients c ON c.id=i.client_id ORDER BY p.payment_date DESC,p.id DESC`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-payment-report.csv"');res.send(csv(rows,['receipt_number','payment_date','invoice_number','client_name','method','reference','amount']));}catch(_e){res.status(500).json({error:'Unable to export payment report.'});}});
 router.get('/requests.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT r.reference,c.name client_name,s.name service_name,r.title,r.priority,r.status,r.created_at,r.updated_at FROM service_requests r JOIN clients c ON c.id=r.client_id JOIN services s ON s.id=r.service_id ORDER BY r.created_at DESC`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-service-requests.csv"');res.send(csv(rows,['reference','client_name','service_name','title','priority','status','created_at','updated_at']));}catch(_e){res.status(500).json({error:'Unable to export service-request report.'});}});
 router.get('/quotations.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT q.quotation_number,c.name client_name,q.issue_date,q.valid_until,q.status,q.subtotal,q.tax_amount,q.discount_amount,q.total_amount,q.client_response_at FROM quotations q JOIN clients c ON c.id=q.client_id ORDER BY q.created_at DESC`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-quotation-report.csv"');res.send(csv(rows,['quotation_number','client_name','issue_date','valid_until','status','subtotal','tax_amount','discount_amount','total_amount','client_response_at']));}catch(_e){res.status(500).json({error:'Unable to export quotation report.'});}});
 router.get('/tasks.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT r.reference,t.title,t.priority,t.status,t.due_date,u.full_name assigned_to,t.created_at,t.completed_at FROM matter_tasks t JOIN service_requests r ON r.id=t.request_id LEFT JOIN users u ON u.id=t.assigned_to ORDER BY t.due_date IS NULL,t.due_date`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-task-report.csv"');res.send(csv(rows,['reference','title','priority','status','due_date','assigned_to','created_at','completed_at']));}catch(_e){res.status(500).json({error:'Unable to export task report.'});}});
 router.get('/clients.csv',auth(['ADMIN']),async(_req,res)=>{try{const[rows]=await pool.query(`SELECT id,name,client_type,email,phone,status,created_at FROM clients ORDER BY created_at DESC`);res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="hyperapex-client-report.csv"');res.send(csv(rows,['id','name','client_type','email','phone','status','created_at']));}catch(_e){res.status(500).json({error:'Unable to export client report.'});}});
 return router;
};
