const express=require('express');const PDFDocument=require('pdfkit');const router=express.Router();
function money(v){return Number(v||0).toLocaleString('en-KE',{minimumFractionDigits:2,maximumFractionDigits:2});}
function titleCase(v){return String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function drawHeader(doc,title,subtitle){doc.fontSize(20).font('Helvetica-Bold').text('HYPERAPEX CONSULTANCY FIRM LIMITED');doc.fontSize(14).font('Helvetica-Bold').text(title);doc.fontSize(9).font('Helvetica').text(subtitle);doc.moveDown(.7);doc.moveTo(50,90).lineTo(545,90).stroke();doc.moveDown(.5);}
function table(doc,headers,rows,widths){const startX=50;let y=doc.y;const rowH=18;doc.fontSize(8).font('Helvetica-Bold');headers.forEach((h,i)=>doc.text(h,startX+widths.slice(0,i).reduce((a,b)=>a+b,0),y,{width:widths[i],continued:false}));y+=rowH;doc.font('Helvetica').fontSize(7);for(const row of rows){if(y>750){doc.addPage();y=50;doc.font('Helvetica-Bold').fontSize(8);headers.forEach((h,i)=>doc.text(h,startX+widths.slice(0,i).reduce((a,b)=>a+b,0),y,{width:widths[i]}));y+=rowH;doc.font('Helvetica').fontSize(7);}row.forEach((v,i)=>doc.text(String(v??'—'),startX+widths.slice(0,i).reduce((a,b)=>a+b,0),y,{width:widths[i],height:rowH,ellipsis:true}));y+=rowH;}doc.y=y+8;}
module.exports=function(pool,auth){router.get('/:type.pdf',auth(['ADMIN']),async(req,res)=>{const type=String(req.params.type).replace(/\.pdf$/,'').toLowerCase();const doc=new PDFDocument({size:'A4',margin:50});const chunks=[];doc.on('data',c=>chunks.push(c));doc.on('end',()=>{const name=`hyperapex-${type}-report.pdf`;res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${name}"`);res.send(Buffer.concat(chunks));});try{const period=new Date().toLocaleDateString('en-KE',{day:'2-digit',month:'long',year:'numeric'});drawHeader(doc,`${titleCase(type)} Report`,`Generated ${period}`);
if(type==='executive'){const[[c]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status='ACTIVE'),0) active FROM clients`);const[[r]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status NOT IN ('COMPLETED','CLOSED')),0) open,COALESCE(SUM(status='COMPLETED'),0) completed FROM service_requests`);const[[t]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status NOT IN ('COMPLETED','CANCELLED')),0) open,COALESCE(SUM(status NOT IN ('COMPLETED','CANCELLED') AND due_date<CURDATE()),0) overdue FROM matter_tasks`);const[[f]]=await pool.query(`SELECT COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected,COALESCE(SUM(balance_due),0) outstanding FROM invoices WHERE status<>'VOID'`);doc.fontSize(11).font('Helvetica-Bold').text('Executive Summary');doc.fontSize(9).font('Helvetica').moveDown(.4);table(doc,['Metric','Value'],[['Total Clients',c.total],['Active Clients',c.active],['Total Matters',r.total],['Open Matters',r.open],['Completed Matters',r.completed],['Open Tasks',t.open],['Overdue Tasks',t.overdue],['Total Invoiced (KES)',money(f.invoiced)],['Collected (KES)',money(f.collected)],['Outstanding (KES)',money(f.outstanding)]],[220,120]);}
else if(type==='financial'){const[[f]]=await pool.query(`SELECT COUNT(*) invoice_count,COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected,COALESCE(SUM(balance_due),0) outstanding FROM invoices WHERE status<>'VOID'`);const[rows]=await pool.query(`SELECT DATE_FORMAT(issue_date,'%Y-%m') period,COUNT(*) invoices,COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected,COALESCE(SUM(balance_due),0) outstanding FROM invoices WHERE status<>'VOID' GROUP BY DATE_FORMAT(issue_date,'%Y-%m') ORDER BY period DESC LIMIT 12`);doc.fontSize(11).font('Helvetica-Bold').text('Financial Summary');doc.fontSize(9).font('Helvetica').moveDown(.4);table(doc,['Metric','Value'],[['Invoices',f.invoice_count],['Invoiced (KES)',money(f.invoiced)],['Collected (KES)',money(f.collected)],['Outstanding (KES)',money(f.outstanding)]],[220,120]);doc.fontSize(11).font('Helvetica-Bold').text('Monthly Performance');doc.moveDown(.3);table(doc,['Period','Invoices','Invoiced','Collected','Outstanding'],rows.map(x=>[x.period,x.invoices,money(x.invoiced),money(x.collected),money(x.outstanding)]),[65,55,100,100,100]);}
else if(type==='invoices'){const[rows]=await pool.query(`SELECT i.invoice_number,c.name,i.issue_date,i.due_date,i.status,i.total_amount,i.amount_paid,i.balance_due FROM invoices i JOIN clients c ON c.id=i.client_id WHERE i.status<>'VOID' ORDER BY i.issue_date DESC`);table(doc,['Invoice','Client','Issue','Due','Status','Total','Balance'],rows.map(x=>[x.invoice_number,x.name,x.issue_date,x.due_date,x.status,money(x.total_amount),money(x.balance_due)]),[65,120,55,55,65,70,70]);}
else if(type==='payments'){const[rows]=await pool.query(`SELECT p.receipt_number,p.payment_date,i.invoice_number,c.name,p.method,p.reference,p.amount FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN clients c ON c.id=i.client_id ORDER BY p.payment_date DESC,p.id DESC`);table(doc,['Receipt','Date','Invoice','Client','Method','Reference','Amount'],rows.map(x=>[x.receipt_number,x.payment_date,x.invoice_number,x.name,x.method,x.reference,money(x.amount)]),[65,55,65,110,75,75,70]);}
else if(type==='quotations'){const[rows]=await pool.query(`SELECT q.quotation_number,c.name,q.issue_date,q.valid_until,q.status,q.total_amount,q.client_response_at FROM quotations q JOIN clients c ON c.id=q.client_id ORDER BY q.created_at DESC`);table(doc,['Quotation','Client','Issue','Valid Until','Status','Total','Response'],rows.map(x=>[x.quotation_number,x.name,x.issue_date,x.valid_until,x.status,money(x.total_amount),x.client_response_at||'—']),[65,120,55,65,70,75,80]);}
else if(type==='requests'){const[rows]=await pool.query(`SELECT r.reference,c.name,s.name service_name,r.title,r.priority,r.status,r.created_at FROM service_requests r JOIN clients c ON c.id=r.client_id JOIN services s ON s.id=r.service_id ORDER BY r.created_at DESC`);table(doc,['Reference','Client','Service','Matter','Priority','Status','Created'],rows.map(x=>[x.reference,x.name,x.service_name,x.title,x.priority,x.status,x.created_at]),[65,90,90,105,60,70,70]);}
else if(type==='tasks'){const[rows]=await pool.query(`SELECT r.reference,t.title,t.priority,t.status,t.due_date,u.full_name FROM matter_tasks t JOIN service_requests r ON r.id=t.request_id LEFT JOIN users u ON u.id=t.assigned_to ORDER BY t.due_date IS NULL,t.due_date`);table(doc,['Matter','Task','Priority','Status','Due','Assigned To'],rows.map(x=>[x.reference,x.title,x.priority,x.status,x.due_date||'—',x.full_name||'Unassigned']),[70,145,65,75,65,125]);}
else if(type==='clients'){const[rows]=await pool.query(`SELECT id,name,client_type,email,phone,status,created_at FROM clients ORDER BY created_at DESC`);table(doc,['ID','Client','Type','Email','Phone','Status'],rows.map(x=>[x.id,x.name,x.client_type,x.email||'—',x.phone||'—',x.status]),[35,120,75,140,90,65]);}
else {res.status(404).json({error:'Unknown PDF report type.'});return;}doc.fontSize(7).font('Helvetica').text('Hyperapex Business Hub • Confidential Management Report',{align:'center'});doc.end();}catch(e){res.status(500).json({error:'Unable to generate PDF report.',detail:e.message});}});return router;};