const express=require('express');
const router=express.Router();
function money(v){return Number(Number(v||0).toFixed(2));}
module.exports=function(pool,auth){
 router.get('/client/:clientId/statement',auth(['ADMIN','STAFF','CLIENT']),async(req,res)=>{try{const requested=Number(req.params.clientId);const clientId=req.user.role==='CLIENT'?Number(req.user.client_id):requested;if(req.user.role==='CLIENT'&&requested!==clientId)return res.status(403).json({error:'Access denied.'});const[[client]]=await pool.query('SELECT id,name,email,phone,address FROM clients WHERE id=?',[clientId]);if(!client)return res.status(404).json({error:'Client not found.'});const[invoices]=await pool.query(`SELECT id,invoice_number,issue_date,due_date,status,total_amount,amount_paid,balance_due FROM invoices WHERE client_id=? AND status<>'VOID' ORDER BY issue_date,id`,[clientId]);const[payments]=await pool.query(`SELECT p.id,p.receipt_number,p.payment_date,p.amount,p.method,p.reference,i.invoice_number FROM payments p JOIN invoices i ON i.id=p.invoice_id WHERE i.client_id=? ORDER BY p.payment_date,p.id`,[clientId]);res.json({client,invoices,payments,totals:{invoiced:invoices.reduce((a,x)=>a+money(x.total_amount),0),paid:invoices.reduce((a,x)=>a+money(x.amount_paid),0),outstanding:invoices.reduce((a,x)=>a+money(x.balance_due),0)}});}catch(_e){res.status(500).json({error:'Unable to load client statement.'});}});
 router.get('/finance',auth(['ADMIN']),async(_req,res)=>{try{const[[summary]]=await pool.query(`SELECT COUNT(*) invoice_count,COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected,COALESCE(SUM(CASE WHEN due_date<CURDATE() AND balance_due>0 THEN balance_due ELSE 0 END),0) overdue,COALESCE(SUM(balance_due),0) outstanding FROM invoices WHERE status<>'VOID'`);const[topClients]=await pool.query(`SELECT c.id,c.name,COUNT(i.id) invoices,COALESCE(SUM(i.total_amount),0) invoiced,COALESCE(SUM(i.amount_paid),0) collected,COALESCE(SUM(i.balance_due),0) outstanding FROM clients c JOIN invoices i ON i.client_id=c.id AND i.status<>'VOID' GROUP BY c.id,c.name ORDER BY outstanding DESC LIMIT 10`);res.json({summary,topClients});}catch(_e){res.status(500).json({error:'Unable to load finance report.'});}});
 router.get('/analytics',auth(['ADMIN']),async(_req,res)=>{try{const[[clients]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status='ACTIVE'),0) active FROM clients`);const[[requests]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status NOT IN ('COMPLETED','CLOSED')),0) open,COALESCE(SUM(status='COMPLETED'),0) completed,COALESCE(SUM(status='CLOSED'),0) closed FROM service_requests`);const[requestStatuses]=await pool.query(`SELECT status,COUNT(*) count FROM service_requests GROUP BY status ORDER BY count DESC`);const[[tasks]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status IN ('TODO','IN_PROGRESS','BLOCKED')),0) open,COALESCE(SUM(status='COMPLETED'),0) completed,COALESCE(SUM(status NOT IN ('COMPLETED','CANCELLED') AND due_date<CURDATE()),0) overdue FROM matter_tasks`);const[[quotations]]=await pool.query(`SELECT COUNT(*) total,COALESCE(SUM(status='SENT'),0) sent,COALESCE(SUM(status='ACCEPTED'),0) accepted,COALESCE(SUM(status='DECLINED'),0) declined,COALESCE(SUM(status='DRAFT'),0) draft,COALESCE(SUM(status='ACCEPTED')/NULLIF(SUM(status IN ('ACCEPTED','DECLINED')),0)*100,0) acceptance_rate FROM quotations`);const[monthlyRevenue]=await pool.query(`SELECT DATE_FORMAT(issue_date,'%Y-%m') month,COALESCE(SUM(total_amount),0) invoiced,COALESCE(SUM(amount_paid),0) collected FROM invoices WHERE status<>'VOID' AND issue_date>=DATE_SUB(CURDATE(),INTERVAL 11 MONTH) GROUP BY DATE_FORMAT(issue_date,'%Y-%m') ORDER BY month`);const[services]=await pool.query(`SELECT s.name,COUNT(DISTINCT r.id) requests,COALESCE(SUM(i.total_amount),0) invoiced,COALESCE(SUM(i.amount_paid),0) collected FROM services s LEFT JOIN service_requests r ON r.service_id=s.id LEFT JOIN invoices i ON i.request_id=r.id AND i.status<>'VOID' GROUP BY s.id,s.name ORDER BY requests DESC,invoiced DESC LIMIT 10`);res.json({clients,requests,requestStatuses,tasks,quotations,monthlyRevenue,services});}catch(_e){res.status(500).json({error:'Unable to load management analytics.'});}});
 return router;
};
